baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'UncleSocks CyBlog'
theme = 'waffles'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[params.about]
title = "waffles"
description = "add description here..."

[[params.socialLinks]]
icon = "fa-brands fa-linkedin"
url = "https://www.linkedin.com/feed/"

[[params.socialLinks]]
icon = "fa-brands fa-github"
url = "https://www.linkedin.com/feed/"

[params]
copyright = "this is a copyright test"