baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Waffles CyBlog Theme'
theme = 'waffles'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[params.about]
title = "Waffles CyBlog Theme"
description = "A minimal Hugo dark theme created for my cybersecurity blog, and inspired by the risotto theme."

[[params.socialLinks]]
icon = "fa-brands fa-linkedin"
url = "https://www.linkedin.com/feed/"

[[params.socialLinks]]
icon = "fa-brands fa-github"
url = "https://www.github.com/"

[params]
copyright = "Made using Hugo and the Waffles theme. Created by UncleSocks, 2024."

[taxonomies]
tag = "tags"
author = "authors"

[pagination]
  disableAliases = false
  pagerSize = 20
